### PR TITLE
mark feature allowing user to permanently highlight data in chart

### PR DESCRIPTION
**Pull request by joshhjacobson**
Slickgrid example to follow.

### CODE REVIEW

**Comment by BigFatDog** [comment]
Thank you so much for your time and efforts on this pull request。

**Comment by joshhjacobson** [comment]
Happy to do it, thanks for walking me through it!

**Comment by BigFatDog** [comment]
@joshhjacobson 
I just found that demo page is not working. I believe source code is good. There are just some minor issues with the `demo.html` itself. 

1. reference path. `demo` directory and `dist` directory are in the same level in rollup dev server. It will work when running `npm run dev`
```
  <script src="../dist/parcoords.standalone.js"></script>
  ...
  <link rel="stylesheet" type="text/css" href="../dist/parcoords.css">
should be:
  <script src="./parcoords.standalone.js"></script>
  <link rel="stylesheet" type="text/css" href="./parcoords.css">
```
2. css style:
```
<div id="plot" class="parcoords" style="height:200px; width=100%;"></div>
// width: 100%
```
3. slick grid doesn't show data. (I remember the demo usage is to check a row in slick grid so as to mark it on parcoords. Now the table is empty)

4. please link `demo.html` to `index.html`

Would you please make a pull request to fix `demo.html`? If you're busy, just tell me and let me do this.

**Comment by joshhjacobson** [comment]
Good catch, I'll fix this either today or early next week and submit a pull request.

**Comment by BigFatDog** [comment]
> Happy to do it, thanks for walking me through it!
It has been my pleasure.

**Pull request merged**
